/**
 * OAuth PKCE (Proof Key for Code Exchange) utilities
 * Implements RFC 7636 for secure OAuth authorization flows
 */

import { createHash } from "node:crypto";

/**
 * Generates a random code_verifier for PKCE flow
 * @returns 32 bytes encoded as base64url (43 characters)
 */
export function generateCodeVerifier(): string {
	const bytes = new Uint8Array(32);
	crypto.getRandomValues(bytes);
	return base64urlEncode(bytes);
}

/**
 * Generates code_challenge from code_verifier using SHA256
 * @param verifier - The code_verifier generated by generateCodeVerifier
 * @returns Base64url-encoded SHA256 hash of the verifier
 */
export function generateCodeChallenge(verifier: string): string {
	const hash = createHash("sha256").update(verifier).digest();
	return base64urlEncode(hash);
}

/**
 * Base64url encoding (RFC 7515 Appendix C)
 * Replaces '+' with '-', '/' with '_', and removes padding
 */
export function base64urlEncode(data: Uint8Array | Buffer): string {
	const base64 = Buffer.from(data).toString("base64");
	return base64.replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/, "");
}

/**
 * Base64url decoding
 */
export function base64urlDecode(encoded: string): Buffer {
	// Add padding if needed
	let padded = encoded;
	while (padded.length % 4 !== 0) {
		padded += "=";
	}
	// Replace URL-safe chars back to standard base64
	padded = padded.replace(/-/g, "+").replace(/_/g, "/");
	return Buffer.from(padded, "base64");
}

/**
 * OAuth token interface with expiration tracking
 */
export interface OAuthToken {
	access_token: string;
	refresh_token?: string;
	token_type: string;
	expires_at: number; // Unix timestamp in milliseconds
	scope?: string;
}

/**
 * Checks if a token is expired or about to expire
 * @param token - The OAuth token to check
 * @param bufferSeconds - Additional buffer time before considering expired (default: 60s)
 * @returns true if token is expired or will expire within bufferSeconds
 */
export function isTokenExpired(
	token: OAuthToken,
	bufferSeconds: number = 60,
): boolean {
	const now = Date.now();
	return token.expires_at <= now + bufferSeconds * 1000;
}

/**
 * Calculates expiration timestamp from expires_in value
 * @param expiresIn - Token validity duration in seconds
 * @returns Unix timestamp in milliseconds
 */
export function calculateExpiresAt(expiresIn: number): number {
	return Date.now() + expiresIn * 1000;
}

/**
 * Creates a sanitized log-friendly representation of token state
 * @param token - The OAuth token to sanitize
 * @returns Object with redacted sensitive fields
 */
export function sanitizeTokenForLogging(
	token: OAuthToken | null,
): Record<string, unknown> {
	if (!token) return { present: false };

	return {
		present: true,
		token_type: token.token_type,
		expires_at: new Date(token.expires_at).toISOString(),
		has_refresh_token: !!token.refresh_token,
		scope: token.scope,
	};
}
