//! Hook event types per spec §3.5.
//!
//! Discriminated union — `kind` is the discriminator. [`parse_hook_event`]
//! validates the raw envelope received from the apohara-hooks-server
//! broadcast and returns a typed event or an error.
//!
//! Mirrors `src/core/hooks/events.ts`. JSON shape is preserved so an
//! envelope generated by the TS path round-trips through the Rust parser
//! unchanged.

use serde::{Deserialize, Serialize};
use thiserror::Error;

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct HookCommonContext {
    #[serde(rename = "paneKey")]
    pub pane_key: String,
    #[serde(default, rename = "taskId", skip_serializing_if = "Option::is_none")]
    pub task_id: Option<String>,
    #[serde(default, rename = "worktreeId", skip_serializing_if = "Option::is_none")]
    pub worktree_id: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum StopReason {
    Completed,
    Interrupted,
    Crashed,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum PermissionScope {
    Once,
    Session,
    Always,
}

/// Strongly-typed hook event. `kind` discriminator matches the TS union
/// (snake_case to align with the wire format).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum HookEvent {
    PreToolUse {
        #[serde(rename = "commonContext")]
        common_context: HookCommonContext,
        #[serde(rename = "toolName")]
        tool_name: String,
        #[serde(rename = "toolInput")]
        tool_input: serde_json::Value,
        timestamp: i64,
    },
    PostToolUse {
        #[serde(rename = "commonContext")]
        common_context: HookCommonContext,
        #[serde(rename = "toolName")]
        tool_name: String,
        #[serde(rename = "toolOutput")]
        tool_output: serde_json::Value,
        #[serde(rename = "durationMs")]
        duration_ms: i64,
        timestamp: i64,
    },
    PostToolUseFailure {
        #[serde(rename = "commonContext")]
        common_context: HookCommonContext,
        #[serde(rename = "toolName")]
        tool_name: String,
        error: String,
        timestamp: i64,
    },
    Stop {
        #[serde(rename = "commonContext")]
        common_context: HookCommonContext,
        reason: StopReason,
        timestamp: i64,
    },
    UserPromptSubmit {
        #[serde(rename = "commonContext")]
        common_context: HookCommonContext,
        prompt: String,
        timestamp: i64,
    },
    PermissionRequest {
        #[serde(rename = "commonContext")]
        common_context: HookCommonContext,
        #[serde(rename = "toolName")]
        tool_name: String,
        #[serde(rename = "toolInput")]
        tool_input: serde_json::Value,
        #[serde(
            default,
            rename = "scopeProposed",
            skip_serializing_if = "Option::is_none"
        )]
        scope_proposed: Option<PermissionScope>,
        timestamp: i64,
    },
}

#[derive(Debug, Error, PartialEq)]
pub enum ParseHookEventError {
    #[error("hook event must be object")]
    NotObject,
    #[error("hook event missing type")]
    MissingType,
    #[error("hook event missing pane_key")]
    MissingPaneKey,
    #[error("{field} must be string")]
    FieldMustBeString { field: &'static str },
    #[error("{field} must be number")]
    FieldMustBeNumber { field: &'static str },
    #[error("invalid stop reason: {0}")]
    InvalidStopReason(String),
    #[error("unknown hook event type: {0}")]
    UnknownType(String),
}

/// Raw wire envelope as broadcast by `apohara-hooks-server`. Field names
/// stay snake_case to match the server output.
#[derive(Debug, Deserialize)]
struct RawEnvelope {
    #[serde(default, rename = "type")]
    event_type: Option<String>,
    #[serde(default)]
    pane_key: Option<String>,
    #[serde(default)]
    task_id: Option<String>,
    #[serde(default)]
    worktree_id: Option<String>,
    #[serde(default)]
    payload: Option<serde_json::Value>,
}

/// Parse a raw broadcast envelope into a typed [`HookEvent`]. Mirrors
/// `parseHookEvent` from the TS module exactly — same field validation,
/// same error messages.
pub fn parse_hook_event(raw: &serde_json::Value) -> Result<HookEvent, ParseHookEventError> {
    if !raw.is_object() {
        return Err(ParseHookEventError::NotObject);
    }
    let env: RawEnvelope =
        serde_json::from_value(raw.clone()).map_err(|_| ParseHookEventError::NotObject)?;
    let event_type = env.event_type.ok_or(ParseHookEventError::MissingType)?;
    let pane_key = env.pane_key.ok_or(ParseHookEventError::MissingPaneKey)?;
    let common = HookCommonContext {
        pane_key,
        task_id: env.task_id,
        worktree_id: env.worktree_id,
    };
    let payload = env.payload.unwrap_or(serde_json::Value::Null);
    let p = payload.as_object();
    let get = |k: &'static str| -> Option<&serde_json::Value> { p.and_then(|m| m.get(k)) };

    match event_type.as_str() {
        "pre_tool_use" => Ok(HookEvent::PreToolUse {
            common_context: common,
            tool_name: require_string(get("tool_name"), "tool_name")?,
            tool_input: get("tool_input").cloned().unwrap_or(serde_json::Value::Null),
            timestamp: require_number(get("timestamp"), "timestamp")?,
        }),
        "post_tool_use" => Ok(HookEvent::PostToolUse {
            common_context: common,
            tool_name: require_string(get("tool_name"), "tool_name")?,
            tool_output: get("tool_output").cloned().unwrap_or(serde_json::Value::Null),
            // Match TS: missing duration_ms defaults to 0.
            duration_ms: get("duration_ms")
                .and_then(|v| v.as_i64())
                .unwrap_or(0),
            timestamp: require_number(get("timestamp"), "timestamp")?,
        }),
        "post_tool_use_failure" => Ok(HookEvent::PostToolUseFailure {
            common_context: common,
            tool_name: require_string(get("tool_name"), "tool_name")?,
            error: require_string(get("error"), "error")?,
            timestamp: require_number(get("timestamp"), "timestamp")?,
        }),
        "stop" => {
            let reason_str = require_string(get("reason"), "reason")?;
            let reason = match reason_str.as_str() {
                "completed" => StopReason::Completed,
                "interrupted" => StopReason::Interrupted,
                "crashed" => StopReason::Crashed,
                other => return Err(ParseHookEventError::InvalidStopReason(other.to_string())),
            };
            Ok(HookEvent::Stop {
                common_context: common,
                reason,
                timestamp: require_number(get("timestamp"), "timestamp")?,
            })
        }
        "user_prompt_submit" => Ok(HookEvent::UserPromptSubmit {
            common_context: common,
            prompt: require_string(get("prompt"), "prompt")?,
            timestamp: require_number(get("timestamp"), "timestamp")?,
        }),
        "permission_request" => {
            let scope_proposed = match get("scope_proposed") {
                Some(serde_json::Value::String(s)) => match s.as_str() {
                    "once" => Some(PermissionScope::Once),
                    "session" => Some(PermissionScope::Session),
                    "always" => Some(PermissionScope::Always),
                    _ => None,
                },
                _ => None,
            };
            Ok(HookEvent::PermissionRequest {
                common_context: common,
                tool_name: require_string(get("tool_name"), "tool_name")?,
                tool_input: get("tool_input").cloned().unwrap_or(serde_json::Value::Null),
                scope_proposed,
                timestamp: require_number(get("timestamp"), "timestamp")?,
            })
        }
        other => Err(ParseHookEventError::UnknownType(other.to_string())),
    }
}

fn require_string(
    v: Option<&serde_json::Value>,
    field: &'static str,
) -> Result<String, ParseHookEventError> {
    match v {
        Some(serde_json::Value::String(s)) => Ok(s.clone()),
        _ => Err(ParseHookEventError::FieldMustBeString { field }),
    }
}

fn require_number(
    v: Option<&serde_json::Value>,
    field: &'static str,
) -> Result<i64, ParseHookEventError> {
    match v {
        Some(serde_json::Value::Number(n)) => n
            .as_i64()
            .or_else(|| n.as_f64().map(|f| f as i64))
            .ok_or(ParseHookEventError::FieldMustBeNumber { field }),
        _ => Err(ParseHookEventError::FieldMustBeNumber { field }),
    }
}
