/**
 * multica #11 — strict RFC 4122 v4 UUID validation + parsing.
 *
 * Most of the orchestration DB (tasks, contexts, runs) keys on UUIDs
 * generated by `crypto.randomUUID()`. Without strict validation at
 * trust boundaries (HTTP loopback, MCP RPCs, CLI flags) a caller can
 * smuggle path-like strings, SQL fragments, or other junk into a slot
 * that the rest of the codebase assumes is a clean UUID. This module
 * is the central choke point.
 *
 * Strict v4 only: version nibble must be `4`, variant nibble must be
 * one of `8`, `9`, `a`, `b`. Hyphens are required at the canonical
 * positions. The nil UUID (all zeros) is rejected by design — it's
 * never a legitimate value in this codebase.
 */

// `i` flag accepts uppercase hex; we normalize to lowercase on parse.
const UUID_V4_REGEX =
	/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;

export type Uuid = string & { readonly __brand: "uuid" };

export function isValidUuid(str: string): boolean {
	if (typeof str !== "string") return false;
	if (str.length !== 36) return false;
	return UUID_V4_REGEX.test(str);
}

export function parseUuid(str: string): Uuid | null {
	if (!isValidUuid(str)) return null;
	return str.toLowerCase() as Uuid;
}
