// AUTO-GENERATED by crates/apohara-types/src/bin/generate_types.rs
// DO NOT EDIT BY HAND. Run `bun run generate-types` to regenerate.
// Generated: 2026-05-22T13:57:04.967169490+00:00

export const APOHARA_TYPES_VERSION = "1.0.0-dev";
