// AUTO-GENERATED by crates/apohara-types/src/bin/generate_types.rs
// DO NOT EDIT BY HAND. Run `bun run generate-types` to regenerate.
//
// Source of truth: every `#[derive(TS)]` type in the Rust workspace.
// ts-rs emits one file per type at `crates/<X>/bindings/<TypeName>.ts`
// and this binary aggregates them here.

export const APOHARA_TYPES_VERSION = "1.0.0-dev";

// from `Band`
export type Band = "hot" | "warm" | "cool" | "idle";

// from `Capability`
export type Capability = "session_fork" | "session_resume" | "setup_helper" | "context_usage" | "compact_boundary" | "native_mcp_tools" | "slash_commands" | "bash_tool" | "edit_tool" | "read_tool" | "json_stream" | "stderr_structured" | "osc_title_updates" | "ask_user_question" | "permission_request" | "agent_hooks" | "roster_hardening" | "drift_detection" | "sandbox_aware";

// from `EventKind`
export type EventKind = "mcp_tool_invoked" | "mcp_rate_limited" | "policy_violation" | "permission_granted" | "permission_denied" | "path_safety_violation" | "sandbox_bypassed" | "security_violation" | "ledger_entry_written" | "ledger_verify_failed" | "guardrails_bypassed" | "hook_event" | "manifest_drift";

// from `Intent`
export type Intent = "implement" | "refactor" | "debug" | "document" | "test" | "explain" | "review" | "other";

// from `SymbolKind`
/**
 * Kind of symbol being referenced. Mirrors the language-agnostic categories
 * the indexer exposes.
 */
export type SymbolKind = "function" | "class" | "type" | "module" | "constant" | "trait" | "enum" | "other";

// from `SymbolRef`
/**
 * Stable reference to a symbol within the workspace.
 *
 * Two `SymbolRef`s are equal iff their `(file, symbol, kind)` triple matches
 * exactly. This is what `conflict_matrix::check` intersects on.
 */
export type SymbolRef = { file: string, symbol: string, kind: SymbolKind, };

// from `TaskSymbolManifest`
/**
 * The set of symbols a single task intends to touch, classified by intent.
 *
 * `reads` is the most permissive bucket (read ∩ read parallelizes), `writes`
 * blocks any other write or read of the same symbol, and `renames` is the
 * most disruptive — it always blocks every other access because the symbol
 * identity itself is changing.
 */
export type TaskSymbolManifest = { reads: Array<SymbolRef>, writes: Array<SymbolRef>, renames: Array<SymbolRef>, };
