@echo off
REM apohara-claude-hook.cmd — Windows equivalent of apohara-claude-hook.sh
REM Always exits 0 (NEVER fails the CLI). 2s curl timeout.
REM Hash: sha256:PLACEHOLDER (regenerated by installer)

setlocal enabledelayedexpansion

set "ENDPOINT=%USERPROFILE%\.apohara\sockets\hooks-endpoint.json"
if not exist "%ENDPOINT%" exit /b 0

REM Parse endpoint file via PowerShell
for /f "delims=" %%P in ('powershell -NoProfile -Command "(Get-Content '%ENDPOINT%' | ConvertFrom-Json).port"') do set PORT=%%P
for /f "delims=" %%T in ('powershell -NoProfile -Command "(Get-Content '%ENDPOINT%' | ConvertFrom-Json).token"') do set TOKEN=%%T

if "%PORT%"=="" exit /b 0
if "%TOKEN%"=="" exit /b 0

REM Read stdin into PAYLOAD
set "PAYLOAD="
for /f "delims=" %%L in ('more') do set "PAYLOAD=!PAYLOAD!%%L"
if "%PAYLOAD%"=="" set "PAYLOAD={}"

REM Derive the server's snake_case discriminant from the PascalCase
REM hook_event_name carried on stdin, mapped via PowerShell. Falls back to
REM APOHARA_HOOK_TYPE, then "unknown".
set "EVENT_TYPE="
for /f "delims=" %%E in ('powershell -NoProfile -Command "$p = $env:PAYLOAD | ConvertFrom-Json; switch ($p.hook_event_name) { 'PreToolUse' {'pre_tool_use'} 'PostToolUse' {'post_tool_use'} 'PostToolUseFailure' {'post_tool_use_failure'} 'Stop' {'stop'} 'StopFailure' {'stop'} 'UserPromptSubmit' {'user_prompt_submit'} 'PermissionRequest' {'permission_request'} default {''} }"') do set EVENT_TYPE=%%E
if "%EVENT_TYPE%"=="" set "EVENT_TYPE=%APOHARA_HOOK_TYPE%"
if "%EVENT_TYPE%"=="" set "EVENT_TYPE=unknown"

REM Compose envelope
set "ENV_JSON={\"type\":\"%EVENT_TYPE%\",\"pane_key\":\"%APOHARA_PANE_KEY%\",\"task_id\":\"%APOHARA_TASK_ID%\",\"worktree_id\":\"%APOHARA_WORKTREE_ID%\",\"payload\":%PAYLOAD%}"

curl.exe -s --max-time 2 -X POST "http://127.0.0.1:%PORT%/event" -H "Authorization: Bearer %TOKEN%" -H "Content-Type: application/json" -d "%ENV_JSON%" >nul 2>&1

exit /b 0