@echo off
REM apohara-claude-hook.cmd — Windows equivalent of apohara-claude-hook.sh
REM Always exits 0 (NEVER fails the CLI). 2s curl timeout.
REM Hash: sha256:PLACEHOLDER (regenerated by installer)

setlocal enabledelayedexpansion

set "ENDPOINT=%USERPROFILE%\.apohara\sockets\hooks-endpoint.json"
if not exist "%ENDPOINT%" exit /b 0

REM Parse endpoint file via PowerShell
for /f "delims=" %%P in ('powershell -NoProfile -Command "(Get-Content '%ENDPOINT%' | ConvertFrom-Json).port"') do set PORT=%%P
for /f "delims=" %%T in ('powershell -NoProfile -Command "(Get-Content '%ENDPOINT%' | ConvertFrom-Json).token"') do set TOKEN=%%T

if "%PORT%"=="" exit /b 0
if "%TOKEN%"=="" exit /b 0

REM Read stdin into PAYLOAD
set "PAYLOAD="
for /f "delims=" %%L in ('more') do set "PAYLOAD=!PAYLOAD!%%L"
if "%PAYLOAD%"=="" set "PAYLOAD={}"

REM Compose envelope
set "ENV_JSON={\"type\":\"%APOHARA_HOOK_TYPE%\",\"pane_key\":\"%APOHARA_PANE_KEY%\",\"task_id\":\"%APOHARA_TASK_ID%\",\"worktree_id\":\"%APOHARA_WORKTREE_ID%\",\"payload\":%PAYLOAD%}"

curl.exe -s --max-time 2 -X POST "http://127.0.0.1:%PORT%/event" -H "Authorization: Bearer %TOKEN%" -H "Content-Type: application/json" -d "%ENV_JSON%" >nul 2>&1

exit /b 0